CREATE TABLE IF NOT EXISTS documents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  filename VARCHAR(512) NOT NULL,
  risk_level VARCHAR(64) NULL DEFAULT NULL,
  clauses_detected INT NULL DEFAULT 0,
  analysis_json LONGTEXT NULL COMMENT 'Full analyze API response JSON',
  uploaded_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
